particuleio/terraform-kubernetes-addons

- modules/scaleway/cert-manager.tf
- modules/scaleway/examples/terraform/main.tf
- modules/scaleway/external-dns.tf
- modules/scaleway/locals-scaleway.tf
- modules/scaleway/templates/cert-manager-cluster-issuers.yaml
- modules/scaleway/templates/cert-manager-cluster-issuers.yaml.tpl
- modules/scaleway/variables-scaleway.tf
Add cert-manager for scaleway
Add scaleway webhook for DNS-01 challenge
Support for DNS-01 and HTTP-01 challenges
> feat: scaleway cert manager

- modules/aws/aws-load-balancer-controller.tf
Signed-off-by: Kevin Lefevre <lefevre.kevin@gmail.com>
> fix(aws): load balancer controller service account annotation

- modules/aws/aws-ebs-csi-driver.tf
- modules/aws/iam/aws-ebs-csi-driver.json
- modules/aws/variables-aws.tf
* enable the use of `gp3` volumes
* enable migration of in-tree volume when EKS enable the feature gate
> feat: add aws-ebs-csi-driver

- .github/workflows/terraform.yml
- README.md
- modules/aws/README.md
- modules/aws/strimzi-kafka-operator.tf
- modules/aws/versions.tf
- modules/scaleway/README.md
- modules/scaleway/strimzi-kafka-operator.tf
- modules/scaleway/versions.tf
- strimzi-kafka-operator.tf
- variables.tf
- versions.tf
* Bump Kubernetes provider and Helm to v2
* Add strimzi kafka operator
* New README with table per provider
* remove unused linter
> feat: update 02/2021

- flux2.tf
Signed-off-by: Kevin Lefevre <lefevre.kevin@gmail.com>
> fix: flux2 breaks module if disabled

- modules/aws/thanos.tf
Fix the latest commit that breaks thanos setup
> fix: revert recent breaking thanos change

- .github/renovate.json
- helm-dependencies.yaml
Release stacked change in main
> release: weekly release

- prometheus-adapter.tf
Use correct url to access Prometheus server
Signed-off-by: Tine Jozelj <tine@tjo.space>
> fix(prometheus-adapter): use correct url (#84)

- .github/renovate.json
- .mergify.yml
- README.md
- helm-dependencies.yaml
- modules/aws/README.md
- modules/aws/cluster-autoscaler.tf
- modules/scaleway/README.md
- modules/scaleway/examples/terraform/README.md
This PR release a new tag with latest changelog
> release: release latest changes

- kube-prometheus.tf
> fix: sync prometheus dashboard between modules

- .github/workflows/terraform.yml
- flux2.tf
- helm-dependencies.yaml
- kube-prometheus.tf
> release: release new changes

- .github/workflows/terraform.yml
- flux2.tf
- helm-dependencies.yaml
- kube-prometheus.tf
Reverts particuleio/terraform-kubernetes-addons#131
> Revert "release: release new changes"

- .github/workflows/terraform.yml
- flux2.tf
- helm-dependencies.yaml
- kube-prometheus.tf
> release: latest changes

- modules/aws/aws-ebs-csi-driver.tf
> fix: breaking change in helm chart

- modules/scaleway/README.md
- modules/scaleway/kube-prometheus.tf
- modules/scaleway/locals-scaleway.tf
- modules/scaleway/loki-stack.tf
- modules/scaleway/thanos-memcached.tf
- modules/scaleway/thanos-storegateway.tf
- modules/scaleway/thanos-tls-querier.tf
- modules/scaleway/thanos.tf
- modules/scaleway/versions.tf
fixes #103 
Add Thanos and Loki depending on S3 bucket. S3 bucket are not created automatically because terraform aws provider use S3 api call not yet implemented by scaleway S3 api:
```
Error: error getting S3 Bucket request payment: NotImplemented: The requested resource is not implemented
status code: 501, request id: tx225ec6c232d24ba0a16ef-00607047a6, host id: tx225ec6c232d24ba0a16ef-00607047a6 
```
> feat(charts): add loki and thanos for scaleway

- .github/workflows/terraform.yml
- .pre-commit-config.yaml
- modules/aws/kube-prometheus.tf
- modules/aws/loki-stack.tf
- modules/aws/thanos.tf
- modules/scaleway/kube-prometheus.tf
- modules/scaleway/loki-stack.tf
- modules/scaleway/thanos.tf
Signed-off-by: Kevin Lefevre <lefevre.kevin@gmail.com>
> chore: update CI and code for TF 0.15 compatibility

- flux2.tf
- helm-dependencies.yaml
- modules/aws/kube-prometheus.tf
- modules/aws/loki-stack.tf
- modules/aws/thanos.tf
> release: latest release

- flux2.tf
- helm-dependencies.yaml
- modules/aws/aws-load-balancer-controller.tf
Releases latest changes and fixes
> release: latest fixes

- helm-dependencies.yaml
- modules/aws/iam/aws-ebs-csi-driver.json
> release: latest change

- helm-dependencies.yaml
- modules/aws/aws-ebs-csi-driver.tf
> release: fix ebs csi driver

- modules/aws/aws-ebs-csi-driver.tf
- modules/aws/aws-for-fluent-bit.tf
- modules/aws/aws-load-balancer-controller.tf
- modules/aws/cert-manager.tf
- modules/aws/cluster-autoscaler.tf
- modules/aws/external-dns.tf
- modules/aws/kube-prometheus.tf
- modules/aws/prometheus-cloudwatch-exporter.tf
- modules/aws/thanos-storegateway.tf
- modules/aws/thanos.tf
- modules/aws/vault.tf
Signed-off-by: Kevin Lefevre <lefevre.kevin@gmail.com>
Fixes #390
> fix: add tags to AWS resources that support it

- loki-stack.tf
- modules/aws/loki-stack.tf
- modules/scaleway/loki-stack.tf
loki values file are incorrect since switching to loki charts from loki-stack
> fix: loki indent

- README.md
- helm-dependencies.yaml
- kong-crds.tf
- kube-prometheus-crd.tf
- modules/aws/README.md
- modules/aws/vault.tf
- modules/aws/versions.tf
- modules/azure/README.md
- modules/azure/version.tf
- modules/scaleway/README.md
- modules/scaleway/versions.tf
- versions.tf
> feat: weekly release (squashed to avoid reverted breaking change)

- README.md
- cert-manager-csi-driver.tf
- cert-manager.tf
- helm-dependencies.yaml
- modules/aws/README.md
- modules/aws/cert-manager-csi-driver.tf
- modules/aws/cert-manager.tf
- modules/azure/README.md
- modules/azure/cert-manager-csi-driver.tf
- modules/scaleway/README.md
- modules/scaleway/cert-manager-csi-driver.tf
- modules/scaleway/cert-manager.tf
- variables.tf
> feat: add cert-manager csi helm chart

- .github/workflows/terraform.yml
- .tool-versions
> chore: test workflows

- README.md
- modules/aws/README.md
- modules/aws/versions.tf
- modules/azure/README.md
- modules/azure/version.tf
- modules/scaleway/README.md
- modules/scaleway/versions.tf
- versions.tf
> fix: pin TLS module version to 3.x

- helm-dependencies.yaml
Fixing secrets-csi-driver version + helm repo
> fix(charts): secrets-csi-driver version + helm repo

- README.md
- flux2.tf
- modules/aws/README.md
- modules/aws/versions.tf
- modules/azure/README.md
- modules/azure/version.tf
- modules/scaleway/README.md
- modules/scaleway/versions.tf
- versions.tf
> feat: upgrade to latest flux v0.32.0

- README.md
- flux2.tf
- helm-dependencies.yaml
- modules/aws/README.md
- modules/aws/aws-ebs-csi-driver.tf
- modules/aws/cluster-autoscaler.tf
- modules/aws/versions.tf
- modules/azure/README.md
- modules/azure/version.tf
- modules/scaleway/README.md
- modules/scaleway/versions.tf
- versions.tf
> feat(release): release latest changes

- README.md
- flux2.tf
- versions.tf
> feat: update Flux2 version and Flux2 provider

- README.md
- flux2.tf
- helm-dependencies.yaml
- modules/aws/versions.tf
- modules/azure/version.tf
- modules/scaleway/versions.tf
- versions.tf
> feat(release): release latest changes 9.2.0

- README.md
- modules/aws/README.md
- modules/aws/versions.tf
- modules/azure/README.md
- modules/azure/version.tf
- modules/scaleway/README.md
- modules/scaleway/versions.tf
- versions.tf
> feat: loosen flux version

- modules/aws/aws-ebs-csi-driver.tf
- modules/aws/aws-efs-csi-driver.tf
> fix: deprecate source_json

- loki-stack.tf
- modules/aws/loki-stack.tf
- modules/scaleway/loki-stack.tf
- promtail.tf
When loki reaches 3.X, services name change.
Here update default values.
> feat(loki): post 3.X update

- kube-prometheus.tf
- modules/aws/kube-prometheus.tf
- modules/scaleway/kube-prometheus.tf
> feat: ignore annotations and labels on prometheus namespace

- .github/workflows/release.yml
- helm-dependencies.yaml
- kube-prometheus.tf
- modules/aws/kube-prometheus.tf
- modules/aws/loki-stack.tf
- modules/scaleway/kube-prometheus.tf
- modules/scaleway/loki-stack.tf
> feat: release latest changes

- modules/aws/README.md
- modules/aws/kube-prometheus.tf
- modules/aws/loki-stack.tf
- modules/aws/s3-logging.tf
- modules/aws/thanos.tf
- modules/aws/velero.tf
> feat: add bucket logging and versionning by default

- modules/aws/README.md
- modules/aws/aws-load-balancer-controller.tf
- modules/aws/iam/aws-load-balancer-controller.json
> feat: update IAM logic for aws-load-balancer-controller

- .github/workflows/renovate.yaml
> chore(ci): use GH action for renovate check

- modules/google/external-dns.tf
The goal of this PR is to remove unused code in external-dns module.
> fix: remove unused test code

- modules/google/cert-manager.tf
The purpose of this PR is to add missing condition in cert-manager addons.
> fix: missing conditions on cert-manager addons on google cloud

- modules/aws/ingress-nginx.tf
- modules/google/ingress-nginx.tf
- modules/scaleway/ingress-nginx.tf
New attribute, keeping old behavior.
> fix(ingress-nginx): allowSnippetAnnotations new values

- .pre-commit-config.yaml
- ingress-nginx.tf
- modules/aws/ingress-nginx.tf
- modules/google/ingress-nginx.tf
- modules/scaleway/ingress-nginx.tf
> feat: add support for custom labels and annotations on ingress-nginx

- modules/scaleway/templates/cert-manager-cluster-issuers.yaml.tpl
fix formatting of cert manager cluster-issuer template
> fix: formatting of cert manager cluster-issuer template

- .pre-commit-config.yaml
- README.md
- modules/aws/README.md
- modules/azure/README.md
- modules/google/README.md
- modules/google/cert-manager.tf
- modules/google/data.tf
- modules/google/external-dns.tf
- modules/google/kube-prometheus.tf
- modules/google/loki-stack.tf
- modules/google/thanos-receive.tf
- modules/google/thanos.tf
- modules/scaleway/README.md
- variables.tf
- **fix(google/cert-manager): better conditions on metrics**
- **fix(google/thanos): improve service account and conditions**
- **fix(google/data): compute project number automatically**
- **fix(google/cert-manager): better conditions on metrics**
- **fix(google/loki): compute gs service account with data source**
- **feat(google/thanos-receive): add Thanos in receiver mode**
- **feat(google/kube-prometheus-stack): allow thanos receiver & infer bucket location from datasources**
- **feat(google/thanos-receive): add Thanos receiver to global variable**
> feat: google fixes

- helm-dependencies.yaml
> feat(helm): uses OCI references to deploy bitnami charts

- flux2.tf
> chore(flux): bump flux to 2.3.0

- modules/google/velero.tf
> fix(velero): fix iam creation declaration

- modules/aws/thanos-storegateway.tf
- modules/aws/thanos-tls-querier.tf
> fix(aws/thanos): update declaration to match oci naming

- modules/google/README.md
- modules/google/kube-prometheus.tf
> fix(kube-prometheus-stack): use correct sa when binding workload identity

- helm-dependencies.yaml
Reverts particuleio/terraform-kubernetes-addons#3347
> Revert "feat(charts): update helm release velero to 10.0.0 (was 8.7.2)"

- modules/aws/aws-ebs-csi-driver.tf
- modules/aws/aws-efs-csi-driver.tf
- modules/aws/aws-for-fluent-bit.tf
- modules/aws/aws-load-balancer-controller.tf
- modules/aws/cert-manager.tf
- modules/aws/cluster-autoscaler.tf
- modules/aws/cni-metrics-helper.tf
- modules/aws/external-dns.tf
- modules/aws/kube-prometheus.tf
- modules/aws/loki-stack.tf
- modules/aws/prometheus-cloudwatch-exporter.tf
- modules/aws/thanos-storegateway.tf
- modules/aws/thanos.tf
- modules/aws/velero.tf
- modules/aws/yet-another-cloudwatch-exporter.tf
Reverts particuleio/terraform-kubernetes-addons#3458
> Revert "feat(tf): update terraform terraform-aws-modules/iam/aws to 6.2.1 (was 5.60.0)"
