particuleio/terraform-kubernetes-addons

- modules/aws/kube-prometheus.tf
In `modules/aws/kube-prometheus.tf`, the Grafana's Thanos-replicate dashboard contains a typo.
Closes #65
> fix: Use proper URL for thanos-replicate dashboard

- modules/aws/thanos.tf
Create the thanos policy only if the thanos bucket is created.
Closes #66
> fix: Create thanos policy if bucket is created

- modules/aws/loki-stack.tf
[Extra volumes](https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml#L140) in promtail chart are lists so they cannot be merged when merging user values and our [own values](https://github.com/particuleio/terraform-kubernetes-addons/blob/v1.28.1/modules/aws/loki-stack.tf#L89)
This breaks TLS if a user adds a new `extraVolume` without adding the TLS one (and the user shouldn't have to). The solution is to use the `defaultVolume` included in the chart.
With this we can have our custom config and let user override without issue
> fix: promtail volume override

- modules/aws/README.md
- modules/aws/vault.tf
Use Vault helm chart to deploy by default:
* 3 vault nodes backed by raft storage
*  Auto unseal with managed KMS Key or existing one
> feat: support vault HA on AWS

- README.md
- kong-crds.tf
- kong.tf
- kube-prometheus-crd.tf
- kube-prometheus.tf
- modules/aws/README.md
- modules/aws/kong-crds.tf
- modules/aws/kube-prometheus-crd.tf
- modules/aws/kube-prometheus.tf
- modules/scaleway/README.md
- modules/scaleway/kong-crds.tf
- modules/scaleway/kube-prometheus.tf
This PR adds logic to handle CRDs lifecycle with TF because it is not handle automatically by Helm 3 and few chart implements CRDs lifecycle (eg. cert-manager does).
Fixes #70
> feat: add CRD handling for Kong and Prometheus

- flux2.tf
I have a mono repo and want to keep the flux2 configs in a different branch and control when they are merged into master so i can lock down the master branch
This change adds an optional variable `flux_sync_branch` so we can push flux config to a different branch but keep it in sync with the master branch
eg:
```
branch                   = "flux-system"
flux_sync_branch         = "main"
```
with something like this, the changes are pushed to flux-system branch but the k8s cluster using flux is configured to sync with the main branch
> feat: option to allow pushing the flux2 configs to a different branch

- modules/aws/aws-ebs-csi-driver.tf
- modules/aws/iam/aws-ebs-csi-driver.json
fix: Use arn partition variable in aws ebs iam policy
This is a follow up after #334 merged. The aws policy was then changed in #346 but did not use the arn partition variable. This PR just updates the iam policy to use the arn partition variable
> fix: Use arn partition variable in aws ebs iam policy

- modules/aws/aws-ebs-csi-driver.tf
- modules/aws/iam/aws-ebs-csi-driver.json
Signed-off-by: Traver Tischio <travertischio@gmail.com>
Co-authored-by: Kevin Lefevre <kevin@particule.io>
> fix: Use arn parttion variable in aws ebs iam policy (#378)

- modules/aws/README.md
- modules/aws/aws-ebs-csi-driver.tf
- modules/aws/iam/aws-ebs-csi-driver_kms.json
This PR adds encryption with custom KMS Key for AWS CSI Driver:
* AWS Default KMS Key
* TF Generated KMS Key
* Existing KMS Key
> feat: add custom encryption for CSI driver

- README.md
- helm-dependencies.yaml
- kyverno.tf
- modules/aws/README.md
- modules/azure/README.md
- modules/scaleway/README.md
Kyverno stores its CRDs in another Helm Chart
Closes #478
Kyverno 2.0 separates the installation of Kyverno in the Kubernetes Cluster and the installation of the Custom Resource Definitions.
If required, install the CRDs beforehand.
> Fix(Kyverno): install CRDs before installing the Helm Release

- README.md
- modules/aws/README.md
- modules/aws/vault.tf
- modules/azure/README.md
- modules/scaleway/README.md
- vault.tf
This PR adds a way to create a CA for Vault cluster that can be used by cert-manager on other cluster to sign TLS client cert
> feat: add vault CA for mTLS cluster

- modules/aws/kube-prometheus.tf
Installing v2.40.1 with kube-prometheus-stack enabled causes crashloopbackoff in grafana pod launch. 
curl command below fails with 404 and returns code 22.
`curl -skf --connect-timeout 60 --max-time 60 -H 'Accept: application/json' -H 'Content-Type: application/json;charset=UTF-8' https://raw.githubusercontent.com/thanos-io/thanos/master/examples/dashboards/bucket_replicate.json`
The correct url is as below:
https://raw.githubusercontent.com/thanos-io/thanos/master/examples/dashboards/bucket-replicate.json
> fix: broken thanos-replicate grafana dashboard link

- README.md
- flux2.tf
- modules/aws/.terraform-docs.yml
- modules/aws/README.md
- modules/aws/versions.tf
- modules/azure/.terraform-docs.yml
- modules/azure/README.md
- modules/azure/version.tf
- modules/scaleway/.terraform-docs.yml
- modules/scaleway/README.md
- modules/scaleway/versions.tf
- versions.tf
BREAKING CHANGE: pin flux version to avoid discrepancy between flux
version and TF provider version.
BREAKING CHANGE: change AWS modules versions to be more flexible
> feat: enhanced provider versions

- modules/aws/aws-ebs-csi-driver.tf
Related to https://github.com/hashicorp/terraform-provider-aws/pull/13000
> fix: KMS alias cannot start with alias/aws

- modules/scaleway/ingress-nginx.tf
Will fix networkpolicies issued with the helm release.
> fix(ingress-nginx): namespace name label for scaleway

- modules/aws/thanos.tf
- modules/scaleway/thanos.tf
Thanos charts release v11 adds a separate grpc service.
> fix: thanos query dedicated grpc service

- README.md
- linkerd2.tf
- loki-stack.tf
- modules/aws/README.md
- modules/aws/loki-stack.tf
- modules/aws/thanos-tls-querier.tf
- modules/aws/thanos.tf
- modules/aws/vault.tf
- modules/aws/versions.tf
- modules/azure/README.md
- modules/azure/version.tf
- modules/scaleway/README.md
- modules/scaleway/loki-stack.tf
- modules/scaleway/thanos-tls-querier.tf
- modules/scaleway/thanos.tf
- modules/scaleway/versions.tf
- vault.tf
- versions.tf
BREAKING CHANGE: upgrade default TLS provider to v4 and remove
deprecated field. Should work without manual changes
> feat: upgrade TLS provider to v4

- modules/aws/cluster-autoscaler.tf
Error I received:
```
Failed to generate AWS EC2 Instance Types: UnauthorizedOperation: You are not authorized to perform this operation.
```
These changes were made because when I run cluster-autoscaler on China, it was in a crashloopback. Once I added the missing policy, it spun up successfully and started running.
https://github.com/kubernetes/autoscaler/issues/3216#issuecomment-644038135
> fix(aws): Adding missing policy for cluster-autoscaler

- ingress-nginx.tf
- modules/aws/ingress-nginx.tf
- modules/scaleway/ingress-nginx.tf
Following ingress-nginx chart upgrade, port name have changed.
> fix(ingress-nginx): metrics port name change

- modules/aws/aws-for-fluent-bit.tf
Adding optional kms key id to encrypt cw log group for fluent bit
> feat: Adding optional kms key id to encrypt cw log group for fluent bit

- modules/aws/loki-stack.tf
- modules/scaleway/loki-stack.tf
Currently you cannot disable canary daemon set as it needs to be moved out from self-monitoring.
More details on this here: https://github.com/grafana/loki/pull/7757
> fix: decouple canary from self-monitoring

- modules/aws/README.md
- modules/aws/aws-efs-csi-driver.tf
- modules/aws/versions.tf
Currently provisioned_throughput_in_mibps is used as a variable to both configure provisioned_throughput_in_mibps and throughput_mode. In November of 2022 AWS [announced](https://aws.amazon.com/blogs/aws/new-announcing-amazon-efs-elastic-throughput/) the elastic throughput mode. The AWS provider added support for the elastic option in https://github.com/hashicorp/terraform-provider-aws/pull/28054 which was released in v4.42.0
This PR opens up the throughput_mode for direct configuration.
This looks like a breaking change for this module.
> feat: Allow throughput_mode elastic configuration in aws efs csi

- README.md
- ingress-nginx.tf
- linkerd-viz.tf
- linkerd2-cni.tf
- modules/aws/README.md
- modules/azure/README.md
- modules/scaleway/README.md
* add a `depends_on` linkerd-control-plane for linkerd-viz
* create new networkPolicies to linkerd-viz when `default_network_policy = true`
* create new networkPolicy to ingress-nginx when `default_network_policy = true`
> fix: add small fixes for linkerd when enabled

- ingress-nginx.tf
- linkerd-viz.tf
- modules/aws/README.md
- modules/aws/ingress-nginx.tf
- modules/scaleway/README.md
- modules/scaleway/ingress-nginx.tf
Linkerd-viz comes with a Prometheus instance with short lived data (6h). The easiest solution when kube-prometheus-stack is already deployed, is to use Prometheus federation for kube-prometheus-stack to scrape Linkerd metrics.
By default, Linkerd-viz comes with network restrictions preventing unmeshed pods to reach its namespace.
> feat: add Linkerd ServerAuthorization manifest

- metrics-server.tf
[v12.8.0](https://github.com/particuleio/terraform-kubernetes-addons/releases/tag/v12.8.0) has updated metrics-server chart to v3.10.0 (https://github.com/particuleio/terraform-kubernetes-addons/pull/1932), which [changed the container port from 4443 to 10250](https://github.com/kubernetes-sigs/metrics-server/compare/metrics-server-helm-chart-3.9.0...metrics-server-helm-chart-3.10.0#diff-388bebf658e7a2cd5fee27a4c120a71575fc2cd0f8ca0ea48d4add89e4e1ddc4R67). 
The networkpolicy `metrics-server-allow-control-plane` was not allowing traffic anymore, resulting in the apiService `v1beta1.metrics.k8s.io` to be down.
> fix: new port for metrics-server-allow-control-plane NetworkPolicy

- modules/aws/kube-prometheus.tf
- modules/aws/loki-stack.tf
- modules/aws/s3-logging.tf
- modules/aws/thanos.tf
- modules/aws/velero.tf
Amazon issued the [article](https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/) recently saying that all newly created buckets will by default have S3 Block Public Access enabled and ACLs disabled.
It's been already taken into account in the underlying module in [this](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/pull/226) PR but they changed the defaults, and this brakes the kube-prometheus-stack module
This PR fixes this issue
> fix: Fix "The bucket does not allow ACLs" error for thanos S3 bucket

- modules/aws/cert-manager.tf
- modules/aws/templates/cert-manager-cluster-issuers.yaml.tpl
In case someone's doing certificates  cross-account, the following resources assigning/assuming roles and permissions are needed
For example, cert-manager needs to create a certificate in the local account using DNS challenge, but there's no Route53 zone in this account
In order to make the challenge, it needs to use the IRSA role which can assume the role in another account where the Route53 zone lives. In turn, this role from the account holding Route53 zone should allow being assumed by this IRSA role
But moreover, the IRSA role says that cert-manager **_can_** assume the role, but not giving the instruction to do this
That's why a custom ClusterIssuer resource is needed with the added role parameter which is currently not supported by the root module
> feat: Add optional role parameter for cert-manager add-on

- modules/google/README.md
- modules/google/external-dns.tf
The purpose of this PR is to add `external-dns` addons for Google Cloud.
> feat: add external-dns addons for google cloud

- README.md
- modules/aws/README.md
- modules/azure/README.md
- modules/google/README.md
- modules/google/ip-masq-agent.tf
- modules/google/manifests/gke-ip-masq/ip-masq-agent-configmap.yaml
- modules/google/manifests/gke-ip-masq/ip-masq-agent-daemonset.yaml
- modules/scaleway/README.md
- variables.tf
The purpose of this PR is to add `ip-masq-agent` addon for Google Cloud.
> feat: add IP masq agent addons for google

- modules/google/thanos.tf
thanos-compactor should have the permission to delete objects in the GCS bucket. In the module we have assigned the role `roles/storage.objectCreator` which doesn't have the `storage.objects.delete` permission.
```bash
level=info ts=2023-08-02T15:28:18.094440054Z caller=blocks_cleaner.go:44 msg="started cleaning of blocks marked for deletion"
level=warn ts=2023-08-02T15:28:18.13448783Z caller=intrumentation.go:67 msg="changing probe status" status=not-ready reason="cleaning marked blocks: delete block: delete 01H4Y0CT7GKNADK3ZSG6MFDXES/meta.json: googleapi: Error 403: thanos-compactor@xxxx-mainnet-0.iam.gserviceaccount.com does not have storage.objects.delete access to the Google Cloud Storage object. Permission 'storage.objects.delete' denied on resource (or it may not exist)., …
```
> fix: add missing iam permissions on thanos in gcp

- modules/google/kube-prometheus.tf
> fix(google): disable coredns monitoring by default on GKE

- modules/aws/kube-prometheus.tf
- modules/google/kube-prometheus.tf
- modules/scaleway/kube-prometheus.tf
Add new local value `thanos_sidecar_enabled` and replace the ternary expression within helm_release.kube-prometheus-stack.values from `local.thanos["enabled"] ? local.values_dashboard_thanos : null,` to `local.thanos["enabled"] && local.kube-prometheus-stack["thanos_dashboard_enabled"] ? local.values_dashboard_thanos : null`
This change adds the ability to use Thanos but optionally enable or disable the built-in Thanos dashboards available at `locals.values_dashboard_thanos`
The changes are made only in aws, google and scaleway kube-prometheus.tf. The root and azure modules do not have Thanos.
I have tested the change locally and on the project where we're utilizing the terraform-kubernetes-addons module and there were no issues. Pre-commit tests have all passed.
Let me know if I need to …
> feat: Add option to disable thanos dashboards in kube-prometheus-stack

- README.md
- modules/aws/README.md
- modules/aws/versions.tf
- modules/azure/README.md
- modules/azure/version.tf
- modules/google/README.md
- modules/google/kube-prometheus.tf
- modules/google/thanos.tf
- modules/google/versions.tf
- modules/scaleway/README.md
- modules/scaleway/versions.tf
- versions.tf
The purpose of this PR is to apply some patches in the google module:
- replace deprecated `gavinbunney/kubectl` which is not working since 1.27 by `alekc/kubectl`.
- fix iam permissions by removing the usage of module when the resources cannot be known in advance.
- fix dependencies
> fix: issue in google module when creating a fresh cluster in 1.27

- modules/aws/velero.tf
Since https://github.com/particuleio/terraform-kubernetes-addons/commit/3ae3e1768531671cea6d5a7af475d49931a615ce, we upgraded the Velero chart to v7 but this requires us to drop the CSI plugin. Without this change, velero is crashlooping due to a duplicate plugin registration
```
An error occurred: unable to register plugin (kind=BackupItemActionV2, name=velero.io/csi-pvc-backupper, command=/plugins/velero-plugin-for-csi) because another plugin is already registered for this kind and name (command=/velero)
```
Ref: https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/README.md#upgrading-to-700
> fix(velero): drop the CSI plugin

- modules/aws/thanos-tls-querier.tf
- modules/google/thanos-tls-querier.tf
- modules/scaleway/thanos-tls-querier.tf
This PR replaces intermediate CA cert (R3) with root CA cert (X1).
In thanos-tls-querier, an intermediate CA cert (R3) was pinned. However, when cert-manager requested a new certificate issued by a higher-level CA (R11), it caused an error `transport: authentication handshake failed: x509: certificate signed by unknown authority`.
In general, intermediate certificates shouldn't be pinned; instead, root certificates should be pinned (e.g., LetsEncrypt X1 root CA). This ensures that the trust chain is maintained when certificates are updated or replaced.
> fix: pin root CA instead of intermediate CA in thanos-tls-querier

- README.md
- modules/aws/variables-aws.tf
- modules/azure/README.md
- modules/google/variables-google.tf
- modules/scaleway/README.md
- modules/scaleway/kube-prometheus.tf
- modules/scaleway/locals-scaleway.tf
- modules/scaleway/loki-stack.tf
- modules/scaleway/thanos.tf
- modules/scaleway/variables-scaleway.tf
- modules/scaleway/velero.tf
- variables.tf
📝 Description
This PR introduces two key changes:
🚀 Feature: New Velero module on Scaleway
Implemented a Velero module to manage backup and recovery solutions on Scaleway.
🛠 Fix: Deprecated ACL attribute on Scaleway buckets
Replaced the deprecated `acl` attribute in Scaleway buckets with the new and recommended terraform resource.
[Deprecation notice](https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/resources/object_bucket#acl)
> feat: add a new velero module on scaleway

- modules/google/README.md
- modules/google/velero.tf
This PR adds support for Velero deployment on GKE clusters. It creates the needed IAM service account and can add a GCS bucket if needed
> feat(google): add velero support

- .github/renovate.json
Currently, whenever a new major version is applied, renovate uses the pretty version which we don't really want
Let's standardize commit messages and show the previous version
> enh(renovate): normalize commit messages and show previous version

- cert-manager.tf
- modules/aws/cert-manager.tf
- modules/google/cert-manager.tf
- modules/scaleway/cert-manager.tf
This was introduced in v1.14.0 of the chart, and installCRDs is deprecated now
> WARNING: `installCRDs` is deprecated, use `crds.enabled` instead.
Ref: official docs (look for `installCRDs`) https://artifacthub.io/packages/helm/cert-manager/cert-manager
> fix(cert-manager): switch from installCRDs to crds.enabled

- .github/renovate.json
The renovate commit message does not show the previous version correctly, there's a typo in `currentVersion`
Ref: https://docs.renovatebot.com/templates/#exposed-config-options
> fix(renovate): correct typo in commit message template

- loki-stack.tf
- modules/aws/loki-stack.tf
- modules/google/loki-stack.tf
- modules/scaleway/loki-stack.tf
We wouldn't get much details from nginx anyway as the pod is nginx OSS, so let's forget about metrics for this component
Ref: https://github.com/grafana/loki/issues/9522#issuecomment-2183086539
> fix(loki): workaround targetdown alert for loki-gateway

- modules/aws/kube-prometheus.tf
- modules/aws/thanos-memcached.tf
- modules/aws/thanos.tf
- modules/google/kube-prometheus.tf
- modules/google/thanos-memcached.tf
- modules/google/thanos-receive.tf
- modules/google/thanos.tf
- modules/scaleway/kube-prometheus.tf
- modules/scaleway/thanos-memcached.tf
- modules/scaleway/thanos.tf
Signed-off-by: Kevin Lefevre <archi@kiln.fi>
> fix(thanos): use oci repo

- modules/google/README.md
- modules/google/loki-stack.tf
When loki needs to delete some chunks backed up on the GCS bucket, it fails due to insufficient permission.
The role objectUser is needed. I added it to the module.
I ran the precommit, everything is green.
> fix: Add role storage.objectUser to loki-stack (allowing deletion)

- modules/aws/kube-prometheus.tf
- modules/aws/loki-stack.tf
- modules/aws/thanos.tf
- modules/aws/velero.tf
This PR adds a flag to allow users to enforce TLS on supporting s3 buckets for the following addons:
- kube-prometheus-stack
- loki-stack
- thanos
- velero
The default value has been set to `false` in order to preserve the current behaviour.
> feat(aws)(loki/thanos/velero): allow users to enforce TLS on s3 buckets

- modules/google/thanos.tf
fix this error:
```
│ Error: Inconsistent conditional result types
│
│   on thanos.tf line 32, in locals:
│   32:     local.thanos["enabled"] && local.thanos["create_bucket"] ? module.thanos_bucket[0] : local.thanos["bucket"]
│     ├────────────────
│     │ local.thanos["bucket"] is "thanos-store-kiln-gcp-telemetry-europe-west1"
│     │ local.thanos["create_bucket"] is "true"
│     │ local.thanos["enabled"] is true
│     │ module.thanos_bucket[0] is object with 4 attributes
│
│ The true and false result expressions must have consistent types. The 'true' value is object, but the 'false' value is string.
```
left hand of the ternary shall return the bucket name, not the full bucket
> fix(thanos): fix comparison for bucket creation

- modules/google/thanos.tf
The Google Cloud Storage bucket used by the Thanos module does not set public access prevention, it's a feature that can avoid mistakenly allowing public access. By default, it will inherit this value from the project, I suggest to offer more secure defaults and enable it explicitly.
Uniform bucket permissions is already the default value, so no need to change that.
> fix(gcp): ensure the thanos bucket prevents public access
